import logging
from pathlib import Path
from typing import Any
from datetime import datetime

from side.utils.paths import get_side_dir

logger = logging.getLogger(__name__)

MONOLITH_TEMPLATE = """# 🏛️ THE MONOLITH
**Strategic Context & Sovereign Intent**
*Last Evolved: {timestamp}*

---

## 🧭 Current Objectives (The North Star)
{objectives}

## 🔨 Active Directives (Tasks)
{tasks}

## 🧠 Recent Intel
{intel}

---
*Generated by Sidelith Sovereign Engine*
"""

async def generate_monolith(db: Any) -> str | None:
    """
    Regenerate the MONOLITH.md file from database state.
    This file serves as the Single Source of Truth for the Agent's context.
    """
    try:
        project_id = db.get_project_id()
        side_dir = get_side_dir()
        monolith_path = side_dir / "MONOLITH.md"
        
        # 1. Fetch Objectives (High Level)
        all_plans = db.list_plans(project_id)
        objectives = [p for p in all_plans if p['type'] == 'objective' and p['status'] != 'done']
        
        # 2. Fetch Tasks (Immediate)
        tasks = [p for p in all_plans if p['type'] == 'task' and p['status'] != 'done']
        
        # 3. Fetch Recent Intel/Insights (from Activity or specific tables)
        # For now, we'll grab recent high-value activities
        activities = db.get_recent_activities(project_id, limit=5)
        
        # Formatting
        def format_list(items):
            if not items:
                return "* *No active items.*"
            return "\n".join([f"* [ ] **{i['title']}** (Due: {i.get('due_date') or 'ASAP'})" for i in items])
            
        def format_intel(acts):
            if not acts:
                return "* *No recent intel.*"
            # Assuming activity schema matches what we log
            out = []
            for a in acts:
                icon = "🔹"
                if a['tool'] == 'scan' or 'audit' in a['tool']: icon = "🛡️"
                if a['tool'] == 'plan': icon = "🧭"
                if a['tier'] == 'critical': icon = "🔴"
                out.append(f"* {icon} {a['action']}")
            return "\n".join(out)

        content = MONOLITH_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            objectives=format_list(objectives),
            tasks=format_list(tasks),
            intel=format_intel(activities)
        )
        
        monolith_path.write_text(content)
        logger.info(f"Monolith evolved at {monolith_path}")
        
        return str(monolith_path)
        
    except Exception as e:
        logger.error(f"Failed to evolve Monolith: {e}")
        return None
