import Link from "next/link";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black text-zinc-400 font-sans p-8 md:p-24 selection:bg-white/10">
            <div className="max-w-3xl mx-auto">
                <Link href="/" className="text-white hover:text-zinc-300 transition-colors mb-8 inline-block">
                    ← Back to CSO.ai
                </Link>

                <h1 className="text-4xl font-bold text-white mb-8 tracking-tight">Terms of Service</h1>

                <div className="space-y-6 text-sm leading-relaxed">
                    <p className="text-zinc-500 font-mono">Last Updated: January 17, 2026</p>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By using CSO.ai, you agree to be bound by these terms. If you do not agree, do not use the service. We provide strategic intelligence as-is, with no guarantee of market outcome.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. Service Description</h2>
                        <p>CSO.ai is a strategic advisor tool. We use Groq&apos;s LPU technology to provide fast, intelligent analysis of your development environment. This service requires a paid &quot;Strategic Token&quot; balance for continuous use.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">3. Strategic Tokens</h2>
                        <p>Tokens are non-refundable once consumed. Consumed tokens represent compute cycles and strategic intelligence generated by the proprietary CSO.ai engine.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. Limitation of Liability & Professional Disclaimer</h2>
                        <p>CSO.ai provides strategic intelligence and forensic analysis for software projects. **You acknowledge that CSO.ai is an AI system, not a licensed professional advisor.** Advice provided should be independently verified before major business or technical commitments.</p>
                        <p className="mt-4">In no event shall CSO.ai be liable for any damages exceeding the total amount paid by you for the service in the twelve (12) months preceding the claim. This includes business loss, loss of investment, or technical failure.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. Data Privacy & GDPR</h2>
                        <p>CSO.ai is privacy-first. Core data remains in your local environment. If you opt-in to Cloud Sync, data is forensically scrubbed of PII before transmission. We comply with EU GDPR, US CCPA, and Turkish KVKK standards for data handling.</p>
                        <p className="mt-4">You retain 100% ownership of your strategic data. You may trigger a &quot;Global Purge&quot; at any time from the dashboard.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">6. Governing Law</h2>
                        <p>These terms are governed by the laws of Turkey and International AI Governance standards. Any disputes shall be settled in the courts of Istanbul.</p>
                    </section>

                    <p className="pt-8 border-t border-white/10 text-xs italic">
                        This is a strategic placeholder for the formal legal Terms of Service.
                    </p>
                </div>
            </div>
        </div>
    );
}
