import Link from "next/link";
import { ChevronRight } from "lucide-react";

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-black text-zinc-400 font-sans p-8 md:p-24 selection:bg-white/10">
            <div className="max-w-3xl mx-auto">
                <Link href="/" className="mb-6 flex items-center gap-2 text-zinc-400 hover:text-white transition-colors">
                    <ChevronRight className="w-4 h-4 rotate-180" /> Back to sidelith.com
                </Link>

                <h1 className="text-4xl font-bold text-white mb-8 tracking-tight">Terms of Service</h1>

                <div className="space-y-6 text-sm leading-relaxed">
                    <p className="text-zinc-400 mb-8 italic">
                        Welcome to Side. By using our platform, you agree to these terms.
                    </p>
                    <p>Please read these Terms of Service ("Terms") carefully before using Side.</p>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By using sidelith.com, you agree to be bound by these terms. If you do not agree, do not use the service. We provide strategic intelligence as-is, with no guarantee of market outcome.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. Service Description</h2>
                        <p>Sidelith is a strategic advisor tool. We use Groq&apos;s LPU technology to provide fast, intelligent analysis of your development environment. This service requires a paid &quot;Side Unit&quot; balance for continuous use.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">3. Side Units</h2>
                        <p>Units are non-refundable once consumed. Consumed units represent compute cycles and strategic intelligence generated by the proprietary Sidelith engine.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. Limitation of Liability & Professional Disclaimer</h2>
                        <p>Sidelith provides strategic intelligence and forensic analysis for software projects. **You acknowledge that Sidelith is an AI system, not a licensed professional advisor.** Advice provided should be independently verified before major business or technical commitments.</p>
                        <p className="mt-4">In no event shall Sidelith be liable for any damages exceeding the total amount paid by you for the service in the twelve (12) months preceding the claim. This includes business loss, loss of investment, or technical failure.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. Data Privacy & GDPR</h2>
                        <p>Sidelith is privacy-first. Core data remains in your local environment. If you opt-in to Cloud Sync, data is forensically scrubbed of PII before transmission. We comply with EU GDPR, US CCPA, and Turkish KVKK standards for data handling.</p>
                        <p className="mt-4">You retain 100% ownership of your strategic data. You may trigger a &quot;Global Purge&quot; at any time from the dashboard.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">6. Governing Law</h2>
                        <p>These terms are governed by the laws of Turkey and International AI Governance standards. Any disputes shall be settled in the courts of Istanbul.</p>
                    </section>

                    <p className="pt-8 border-t border-white/10 text-xs italic">
                        This is a strategic placeholder for the formal legal Terms of Service.
                    </p>
                </div>
            </div>
        </div>
    );
}
